version: "3.8"
services:
  car-server:
    image: evertosilva/car-server:latest
    ports:
      - "3000:3000"

  mysql_db:
    image: mysql:8.0.26
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: car
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE

  redis:
    image: redis:bullseye
    container_name: redis
    ports:
      - "6379:6379"

  spring_api:
    container_name: spring_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

    environment:
      spring.datasource.url: "jdbc:mysql://mysql_db:3306/car?allowPublicKeyRetrieval=true&useSSL=false"
      spring.datasource.username: "root"
      spring.datasource.password: "root"
      spring.redis.host: "redis"
      host_url: "http://car-server:3000"
    depends_on:
      - mysql_db
      - redis
      - car-server
    restart: "on-failure"